platform :ios, '7.0'

pod 'MBProgressHUD', '~> 0.8'
pod 'RESideMenu', '~> 3.4'
pod 'CTAssetsPickerController',  '~> 1.5.0'
pod 'MHVideoPhotoGallery', '~> 1.4'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'NZCircularImageView'
pod 'FRDLivelyButton', '~> 1.1.1'
pod 'DBCamera', '~> 1.1.0'